### ISSUE TITLE
Commit build directory to git?

### ISSUE THREAD

**Issue by sramam** [ramasilveyra/gitpkg#11]
@ramasilveyra , Would you be open to committing the ./build directory to the repo?
Currently, npm installing https://github.com/sramam/gitpgkg (with my fixes for #9) doesn't
work. 

I need to copy the build directory over manually from a local install.

**Comment by ramasilveyra** [comment]
Hello! I'm not a fan of commiting build files, I prefer to use the prepublish npm script.

Using `gitpkg publish` to publish your fork it should create a git tag with the build files, take a look to https://github.com/ramasilveyra/public-registry/tree/gitpkg-v1.0.0-beta.1-gitpkg.

<img src="https://user-images.githubusercontent.com/7464663/27548379-318b38f8-5a6f-11e7-978c-b5a2f6677e61.gif" />

What I know that is failing is publishing to git https urls like `https://github.com/ramasilveyra/public-registry.git` fail due to git asking for input for the username and password. Is this your case?
